# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Laugh_hahaha' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod "AFNetworking"
  # Pods for Laugh_hahaha
  
    pod "Masonry"
    pod "SDWebImage"
    
    #模型转换
    pod "MJExtension"
    
    #加载GIF图
    pod "YLGIFImage"
    
    #下拉刷新
    pod "MJRefresh"

  target 'Laugh_hahahaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Laugh_hahahaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
